import Head from 'next/head';
import Hero from '../components/Hero';
import Map from '../components/Map';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero py={20} pt={36} />
			<Map p={8} />
		</>
	);
}
